-- CS14-1 PostgreSQL schema handover
-- Owner: Zhenyu Zhang
-- Scope: cs14.sql schema export, database deployment reference, and performance-testing baseline.
-- Source of truth: PostgreSQL 16 plus Alembic migrations under backend/alembic/versions/.
-- Deployment baseline: docker-compose Postgres service + backend Alembic startup.
-- Performance baseline: indexed query paths for responses, tracking batches, analytics, and exports.

BEGIN;

CREATE TABLE IF NOT EXISTS researchers (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(255) NOT NULL,
    password_hash varchar(255) NOT NULL,
    name varchar(100) NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT uq_researchers_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS surveys (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    researcher_id integer NOT NULL REFERENCES researchers(id),
    title varchar(255) NOT NULL,
    description text,
    status varchar(20) NOT NULL DEFAULT 'draft',
    share_code varchar(20) NOT NULL,
    share_code_expires_at timestamp without time zone,
    platform_ui_style varchar(40) NOT NULL DEFAULT 'twitter',
    platform_style varchar(32) NOT NULL DEFAULT 'x',
    default_language varchar(10) NOT NULL DEFAULT 'en',
    supported_languages jsonb NOT NULL DEFAULT '["en", "ar", "zh"]'::jsonb,
    num_groups smallint NOT NULL DEFAULT 1,
    group_names jsonb,
    gaze_tracking_enabled boolean NOT NULL DEFAULT true,
    gaze_interval_ms integer NOT NULL DEFAULT 1000,
    click_tracking_enabled boolean NOT NULL DEFAULT true,
    calibration_enabled boolean NOT NULL DEFAULT true,
    calibration_points smallint NOT NULL DEFAULT 9,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    published_at timestamp without time zone,
    CONSTRAINT uq_surveys_share_code UNIQUE (share_code),
    CONSTRAINT ck_surveys_num_groups_positive CHECK (num_groups > 0)
);

CREATE TABLE IF NOT EXISTS survey_posts (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    survey_id integer NOT NULL REFERENCES surveys(id) ON DELETE CASCADE,
    "order" integer NOT NULL,
    original_url text NOT NULL,
    fetched_title text,
    fetched_image_url text,
    fetched_description text,
    fetched_source varchar(255),
    display_title text,
    display_image_url text,
    display_description text,
    source_label varchar(255),
    more_info_label varchar(80),
    display_likes integer NOT NULL DEFAULT 0,
    display_comments_count integer NOT NULL DEFAULT 0,
    display_shares integer NOT NULL DEFAULT 0,
    show_likes boolean NOT NULL DEFAULT true,
    show_comments boolean NOT NULL DEFAULT true,
    show_shares boolean NOT NULL DEFAULT true,
    visible_to_groups jsonb,
    group_overrides jsonb,
    created_at timestamp without time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS post_comments (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id integer NOT NULL REFERENCES survey_posts(id) ON DELETE CASCADE,
    "order" integer NOT NULL,
    author_name varchar(100) NOT NULL,
    author_avatar_url text,
    text text NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS questions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    survey_id integer NOT NULL REFERENCES surveys(id) ON DELETE CASCADE,
    post_id integer REFERENCES survey_posts(id) ON DELETE CASCADE,
    "order" integer NOT NULL,
    question_type varchar(30) NOT NULL,
    text text NOT NULL,
    config jsonb,
    created_at timestamp without time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS survey_responses (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    survey_id integer NOT NULL REFERENCES surveys(id) ON DELETE CASCADE,
    participant_token varchar(64) NOT NULL,
    assigned_group smallint NOT NULL DEFAULT 1,
    randomization_seed varchar(64),
    shown_post_order jsonb,
    user_agent text,
    screen_width integer,
    screen_height integer,
    language varchar(10),
    participant_fingerprint varchar(128),
    status varchar(20) NOT NULL DEFAULT 'in_progress',
    is_preview boolean NOT NULL DEFAULT false,
    is_speed_test_failed boolean NOT NULL DEFAULT false,
    started_at timestamp without time zone NOT NULL DEFAULT now(),
    completed_at timestamp without time zone,
    attention_active_ms integer,
    attention_expected_samples integer,
    attention_detected_samples integer,
    attention_missing_ms integer,
    attention_no_face_periods integer,
    attention_coverage double precision,
    attention_confidence double precision,
    attention_quality varchar(20),
    attention_quality_reason text,
    extra_metadata jsonb,
    CONSTRAINT uq_survey_responses_participant_token UNIQUE (participant_token)
);

CREATE TABLE IF NOT EXISTS participant_interactions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    response_id integer NOT NULL REFERENCES survey_responses(id) ON DELETE CASCADE,
    post_id integer NOT NULL REFERENCES survey_posts(id),
    action_type varchar(20) NOT NULL,
    comment_text text,
    dwell_time_ms integer,
    click_x double precision,
    click_y double precision,
    timestamp timestamp without time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS participant_likes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    response_id integer NOT NULL REFERENCES survey_responses(id) ON DELETE CASCADE,
    post_id integer NOT NULL REFERENCES survey_posts(id) ON DELETE CASCADE,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT uq_participant_like_response_post UNIQUE (response_id, post_id)
);

CREATE TABLE IF NOT EXISTS participant_comments (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    response_id integer NOT NULL REFERENCES survey_responses(id) ON DELETE CASCADE,
    post_id integer NOT NULL REFERENCES survey_posts(id) ON DELETE CASCADE,
    author_name varchar(100),
    text text NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone
);

CREATE TABLE IF NOT EXISTS question_responses (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    response_id integer NOT NULL REFERENCES survey_responses(id) ON DELETE CASCADE,
    question_id integer NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    answer_text text,
    answer_value integer,
    answer_choices jsonb,
    created_at timestamp without time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS calibration_sessions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    response_id integer NOT NULL REFERENCES survey_responses(id) ON DELETE CASCADE,
    status varchar(20) NOT NULL DEFAULT 'in_progress',
    screen_width integer NOT NULL,
    screen_height integer NOT NULL,
    camera_width integer,
    camera_height integer,
    expected_points smallint NOT NULL DEFAULT 9,
    face_detection_rate double precision,
    quality_score double precision,
    passed boolean,
    stability_score double precision,
    quality_reason varchar(255),
    model_type varchar(80),
    model_params jsonb,
    validation_error_px double precision,
    quality varchar(20),
    started_at timestamp without time zone NOT NULL DEFAULT now(),
    completed_at timestamp without time zone,
    CONSTRAINT uq_calibration_sessions_response UNIQUE (response_id)
);

CREATE TABLE IF NOT EXISTS calibration_points (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id integer NOT NULL REFERENCES calibration_sessions(id) ON DELETE CASCADE,
    point_index smallint NOT NULL,
    target_screen_x integer NOT NULL,
    target_screen_y integer NOT NULL,
    samples jsonb NOT NULL,
    samples_count integer NOT NULL,
    face_detection_rate double precision,
    stability_score double precision,
    valid boolean,
    median_left_iris_x double precision,
    median_left_iris_y double precision,
    median_right_iris_x double precision,
    median_right_iris_y double precision,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT uq_session_point UNIQUE (session_id, point_index)
);

CREATE TABLE IF NOT EXISTS gaze_records (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    response_id integer NOT NULL REFERENCES survey_responses(id) ON DELETE CASCADE,
    post_id integer REFERENCES survey_posts(id) ON DELETE SET NULL,
    timestamp_ms bigint NOT NULL,
    screen_x double precision NOT NULL,
    screen_y double precision NOT NULL,
    left_iris_x double precision,
    left_iris_y double precision,
    right_iris_x double precision,
    right_iris_y double precision,
    received_at timestamp without time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS click_records (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    response_id integer NOT NULL REFERENCES survey_responses(id) ON DELETE CASCADE,
    post_id integer REFERENCES survey_posts(id) ON DELETE SET NULL,
    timestamp_ms bigint NOT NULL,
    screen_x double precision NOT NULL,
    screen_y double precision NOT NULL,
    target_element varchar(50),
    received_at timestamp without time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS survey_translations (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    survey_id integer NOT NULL REFERENCES surveys(id) ON DELETE CASCADE,
    language_code varchar(10) NOT NULL,
    translated_fields jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT uq_survey_translation_language UNIQUE (survey_id, language_code)
);

CREATE TABLE IF NOT EXISTS post_translations (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    survey_id integer NOT NULL REFERENCES surveys(id) ON DELETE CASCADE,
    post_id integer NOT NULL REFERENCES survey_posts(id) ON DELETE CASCADE,
    language_code varchar(10) NOT NULL,
    translated_fields jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT uq_post_translation_language UNIQUE (post_id, language_code)
);

CREATE TABLE IF NOT EXISTS question_translations (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    survey_id integer NOT NULL REFERENCES surveys(id) ON DELETE CASCADE,
    question_id integer NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    language_code varchar(10) NOT NULL,
    translated_fields jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT uq_question_translation_language UNIQUE (question_id, language_code)
);

-- Query and eager-loading baseline indexes for performance testing.
CREATE INDEX IF NOT EXISTS ix_surveys_researcher_id ON surveys(researcher_id);
CREATE INDEX IF NOT EXISTS ix_surveys_status ON surveys(status);
CREATE INDEX IF NOT EXISTS ix_survey_posts_survey_id ON survey_posts(survey_id);
CREATE INDEX IF NOT EXISTS ix_questions_survey_id ON questions(survey_id);
CREATE INDEX IF NOT EXISTS ix_questions_post_id ON questions(post_id);
CREATE INDEX IF NOT EXISTS ix_survey_responses_survey_id ON survey_responses(survey_id);
CREATE INDEX IF NOT EXISTS ix_survey_responses_assigned_group ON survey_responses(assigned_group);
CREATE INDEX IF NOT EXISTS ix_survey_responses_language ON survey_responses(language);
CREATE INDEX IF NOT EXISTS ix_survey_responses_status ON survey_responses(status);
CREATE INDEX IF NOT EXISTS ix_survey_responses_is_preview ON survey_responses(is_preview);
CREATE INDEX IF NOT EXISTS ix_participant_interactions_response_id ON participant_interactions(response_id);
CREATE INDEX IF NOT EXISTS ix_participant_interactions_post_id ON participant_interactions(post_id);
CREATE INDEX IF NOT EXISTS ix_participant_interactions_response_post ON participant_interactions(response_id, post_id);
CREATE INDEX IF NOT EXISTS ix_gaze_records_response_id ON gaze_records(response_id);
CREATE INDEX IF NOT EXISTS ix_gaze_records_response_timestamp ON gaze_records(response_id, timestamp_ms);
CREATE INDEX IF NOT EXISTS ix_gaze_records_post_timestamp ON gaze_records(post_id, timestamp_ms);
CREATE INDEX IF NOT EXISTS ix_click_records_response_id ON click_records(response_id);
CREATE INDEX IF NOT EXISTS ix_click_records_response_timestamp ON click_records(response_id, timestamp_ms);
CREATE INDEX IF NOT EXISTS ix_click_records_post_timestamp ON click_records(post_id, timestamp_ms);
CREATE INDEX IF NOT EXISTS ix_survey_translations_survey_language ON survey_translations(survey_id, language_code);
CREATE INDEX IF NOT EXISTS ix_post_translations_survey_language ON post_translations(survey_id, language_code);
CREATE INDEX IF NOT EXISTS ix_post_translations_post_language ON post_translations(post_id, language_code);
CREATE INDEX IF NOT EXISTS ix_question_translations_survey_language ON question_translations(survey_id, language_code);
CREATE INDEX IF NOT EXISTS ix_question_translations_question_language ON question_translations(question_id, language_code);

COMMIT;
